/* Original conceptual geometry and teaching records. Units are illustrative. */
const box = (id,name,p,size,color,explode=[0,0,0]) => ({id,name,p,size,color,explode});
const teal='#397d72', light='#a9c1b3', gold='#dba16c', dark='#355554';
export const samples = [
 {id:'cabinet',name:'Sliding cabinet',category:'Storage',mechanism:'Guided translation',summary:'A rail constrains a drawer to a useful path.',
 parts:[box('frame','Base panel',[0,0,0],[2.5,.16,1.8],light,[0,-.35,0]),box('left','Left side',[-1.17,1,0],[.16,2,1.8],teal,[-.8,0,0]),box('right','Right side',[1.17,1,0],[.16,2,1.8],teal,[.8,0,0]),box('top','Top panel',[0,2,0],[2.5,.16,1.8],light,[0,.8,0]),box('drawer','Drawer',[0,.9,.12],[2.05,.8,1.5],gold,[0,0,1.5]),box('handle','Handle',[0,.9,.96],[.65,.12,.12],dark,[0,0,1.7]),box('rail','Guide rail',[-1.04,.6,0],[.08,.12,1.65],dark,[-.25,0,0])],
 relations:[{from:'rail',to:'drawer',type:'guides_motion',label:'Rail → drawer',mechanism:'A prismatic guide allows translation along one axis and limits transverse movement.',conditions:'The guides remain aligned, engaged and adequately supported.',result:'The drawer can move outward while remaining guided.',intervention:'Removing a guide may permit skewing or jamming. The outcome depends on the remaining supports.'},{from:'left',to:'top',type:'supports',label:'Side → top panel',mechanism:'The side panel provides one part of the load path beneath the top.',conditions:'The joints remain connected and the material can carry the applied load.',result:'Loads can pass from the top into the frame.',intervention:'Removing the side changes the load path; stability depends on the remaining connections.'}],
 tasks:{compose:'Combine a shell, drawer and aligned guides to create accessible storage.',decompose:'One possible decomposition is a shell, drawer, guides and handle. Other storage mechanisms are possible.',intervene:'If a rail becomes misaligned, will the drawer still move freely? Identify the assumed clearance.',transfer:'Compare drawer guides with a sliding door: both constrain translation, with different support and load requirements.'}},
 {id:'chair',name:'Four-leg chair',category:'Seating',mechanism:'Load transfer',summary:'Support geometry connects a seat to the floor.',
 parts:[box('seat','Seat',[0,1.35,0],[2,.2,1.8],gold,[0,.6,0]),box('back','Backrest',[0,2.2,-.8],[2,1.3,.16],teal,[0,.6,-.8]),...[-.8,.8].flatMap((x,i)=>[-.7,.7].map((z,j)=>box(`leg_${i}${j}`,`${i?'Right':'Left'} ${j?'front':'rear'} leg`,[x,.65,z],[.18,1.3,.18],light,[x*.6,-.3,z*.6])))],
 relations:[{from:'seat',to:'leg_00',type:'transfers_load',label:'Seat → supporting leg',mechanism:'An attached leg forms one path for load transfer from the seat toward the floor.',conditions:'The leg joint remains intact, the foot contacts a supporting surface and the load stays within capacity.',result:'The support system can carry the seat and its applied load.',intervention:'Removing one leg reduces the support region; tipping depends on the load position and remaining contacts.'},{from:'back',to:'seat',type:'functional_contribution',label:'Backrest → seating system',mechanism:'The connected backrest provides a surface against which a seated person can lean.',conditions:'Its joints can transmit the resulting forces and moments.',result:'The chair provides back support as well as a seating surface.',intervention:'Removing the backrest removes that support function without necessarily preventing sitting.'}],
 tasks:{compose:'Relate the seat, legs and backrest to seating, support and load transfer.',decompose:'A seat and a support system are one decomposition; four separate legs are not the only possible design.',intervene:'Would a three-contact support arrangement remain stable for this load position? More geometry and load evidence is required.',transfer:'Transfer the support-system role to a table; do not assume identical load capacity.'}},
 {id:'table',name:'Frame-supported table',category:'Surfaces',mechanism:'Structural support',summary:'A surface and frame cooperate to carry a load.',
 parts:[box('top','Tabletop',[0,1.65,0],[3.2,.18,2],gold,[0,.8,0]),box('apron','Front apron',[0,1.35,.8],[2.8,.35,.12],teal,[0,.1,.5]),...[-1.3,1.3].flatMap((x,i)=>[-.8,.8].map((z,j)=>box(`leg_${i}${j}`,`${i?'Right':'Left'} ${j?'front':'rear'} leg`,[x,.8,z],[.2,1.6,.2],light,[x*.3,-.2,z*.5])))],
 relations:[{from:'top',to:'leg_00',type:'transfers_load',label:'Tabletop → leg',mechanism:'A connected support transfers a portion of the tabletop load toward the floor.',conditions:'Joints, material and floor contacts support the applied loading.',result:'The assembly provides an elevated working surface.',intervention:'Removing a support changes load distribution and may change stability.'},{from:'apron',to:'leg_01',type:'constrains_motion',label:'Apron → leg',mechanism:'A sufficiently rigid apron connection can limit relative motion between frame members.',conditions:'The joint geometry and stiffness provide the relevant constraint.',result:'The frame can better resist some lateral deformation.',intervention:'Removing the apron can increase deformation, depending on the other joints.'}],
 tasks:{compose:'Explain how a top and connected frame become a usable elevated surface.',decompose:'Separate the surface from its support system, then consider alternative bases.',intervene:'What extra evidence is needed to predict a safe load? Material, joint properties and dimensions.',transfer:'Compare a chair and table load path while keeping their different use conditions explicit.'}},
 {id:'door',name:'Hinged door',category:'Access',mechanism:'Constrained rotation',summary:'A hinge permits rotation while retaining the panel.',
 parts:[box('post','Frame post',[-1,1.5,0],[.2,3,.3],light,[-.8,0,0]),box('panel','Door panel',[0,1.5,0],[1.8,2.8,.12],teal,[.6,0,0]),box('hinge','Hinge group',[-.92,1.5,.1],[.15,1.8,.16],gold,[-.3,0,.4]),box('handle','Handle',[.65,1.45,.15],[.28,.1,.16],gold,[.7,0,.5])],
 relations:[{from:'hinge',to:'panel',type:'revolute_joint',label:'Hinge → panel',mechanism:'An ideal revolute joint allows rotation about one axis while constraining other relative motions.',conditions:'The hinge remains attached and the panel has clearance along its swing path.',result:'The panel can move between open and closed configurations.',intervention:'Locking the joint blocks the ordinary swing motion; this does not evaluate the strength of the lock.'},{from:'handle',to:'panel',type:'functional_contribution',label:'Handle → panel',mechanism:'The handle provides a grasp location for applying force to the panel.',conditions:'The handle attachment can transmit the applied force.',result:'A person can operate the panel using the handle.',intervention:'Removing the handle removes this grasp location; other ways of moving the door may remain.'}],
 tasks:{compose:'Connect a panel to a frame with hinges to create a movable access boundary.',decompose:'A hinged access system can include a panel, frame, hinges and operating features; a sliding system differs.',intervene:'If the swing path is obstructed, can the hinge alone guarantee opening? No: clearance is a separate condition.',transfer:'Compare a room door and a cabinet door at the level of joint roles, not interchangeable hardware.'}},
 {id:'scissors',name:'Two-blade scissors',category:'Tools',mechanism:'Coupled cutting action',summary:'Relative rotation brings two working edges together.',
 parts:[{...box('blade_a','Blade and handle A',[0,1.2,0],[.22,3.1,.12],teal,[-.7,0,.3]),angle:-.55,handle_ring:true},{...box('blade_b','Blade and handle B',[0,1.2,.16],[.22,3.1,.12],gold,[.7,0,.5]),angle:.55,handle_ring:true},box('pivot','Pivot',[0,1.2,.3],[.3,.3,.22],dark,[0,0,1])],
 relations:[{from:'pivot',to:'blade_a',type:'revolute_joint',label:'Pivot → blade group',mechanism:'The pivot retains the blade groups while allowing relative rotation.',conditions:'The joint stays engaged and the working edges remain appropriately aligned.',result:'The blades can perform an opening and closing motion.',intervention:'Completely locking relative rotation blocks the usual open–close cutting action.'},{from:'blade_a',to:'blade_b',type:'functional_cooperation',label:'Blade A ↔ blade B',mechanism:'The two working edges cooperate during the closing action.',conditions:'Edge geometry, contact, material and applied force permit cutting.',result:'Suitable material can be separated by the cutting action.',intervention:'Misaligning the edges can prevent effective cutting even if rotation remains possible.'}],
 tasks:{compose:'Combine working edges and a pivot, then state the extra conditions needed for cutting.',decompose:'A simplified scissor system contains two blade–handle groups and a pivot; production designs may contain additional pieces.',intervene:'Predict the effect of locking rotation while keeping the other conditions fixed.',transfer:'Compare relative rotation in scissors and a door. The joint role is shared; the whole-object function differs.'}}
];
export function record(sample) {
 return {schema_version:'showcase-1.0',object_id:`illustrative_${sample.id}`,name:sample.name,category:sample.category,geometry:{source:'Original project-authored parameterized illustration',units:'arbitrary; not measured CAD',parts:sample.parts},review_status:'illustrative_not_independently_reviewed',evidence:{type:'expert_hypothesis',source:'Project-authored teaching example; no source-object or physical-test evidence'},relations:sample.relations,reasoning_tasks:sample.tasks,limitations:'Not an accepted dataset record, simulated outcome or measured model result.'};
}
